### PR TITLE
add tr_TR.json

### PR DESCRIPTION
**Pull request by Katsuyuki-Karasawa**
@kyoyacchi
使用了来自kyoyacchi的土耳其语译文。
谢谢你。
日本的json已经被删除。
一些没有完全翻译的部分将在以后完成。

https://github.com/kyoyacchi/pixiv_func_mobile/blob/28b62c3f1b3e1f9c4045fa045c0f0652a53b79ed/lib/app/i18n/i18n_translations.dart#L1053

### CODE REVIEW

**Comment by git-xiaocao** [comment]
I18n有一些新增项目
@lucas-04 
@Katsuyuki-Karasawa

**Comment by git-xiaocao** [comment]
我注意到了你的头像似乎不是正方形的(你好像是个画师)

**Comment by Katsuyuki-Karasawa** [comment]
我已经把它摆平了(插图由一位朋友绘制)

**Comment by Katsuyuki-Karasawa** [comment]
@git-xiaocao mearge pls

**Comment by kyoyacchi** [comment]
@git-xiaocao I don't accept this. I'm the one who translates the Turkish one and you accept him as translator 
Screenshot_20220918-115701

I mean why would you change it to your name in the first place? Did you translate it? Do you know Turkish? I bet you don't even know a single word in Turkish, i want it to be removed please.

Lütfen bu çeviriyi ya kaldırın ya da benim adımı çevirmen olarak kullanın.

İçtenlikle.
Sincerely

**Comment by Katsuyuki-Karasawa** [comment]
@kyoyacchi 
I don't know why you are so angry, but if you want, you can change it to yours and submit a pull request.
I don't think it is right for the OSS to submit a pull request under someone's name without their permission, so I submitted it under my name and icon.

I have no qualms about changing my name to yours, and I would be happy to submit pull requests and ongoing translations as needed.
In fact, I only helped you because you seemed to have stopped because you didn't know how to translate at all.
I think the rest is up to you to decide (and if necessary, I will tell you how to proceed with the translation, so please don't be so angry).

PS: I've included a "Thanks" so I don't want this to be my own personal achievement.

**Comment by kyoyacchi** [comment]
> 
Why wouldn't i be angry? Would you be happy if someone else submit'd ur translation under their name?

It's not like i don't know how to translate. I know and i did translate it. What made you think this way? 

If you don't think is it right for the OSS to submit request under someone's name without their permission, you could've ask me in that PR, i asked if its OK or not, @git-xiaocao said something in Japanese or Chinese whatever it is.
I couldn't understand it so i left it how it was.

F#ck it, i don't care anymore

**Comment by git-xiaocao** [comment]
@kyoyacchi 
Sorry, I see you haven't replied for too long, so I merged his PR.
I will change my name to yours now.
sorry

**Comment by git-xiaocao** [comment]
> said something in Japanese or Chinese whatever it is.

I'm Chinese, don't speak other languages, use Google translate

**Comment by kyoyacchi** [comment]
> @kyoyacchi 
> Sorry, I see you haven't replied for too long, so I merged his PR.
> I will change my name to yours now.
> sorry

No problem, but was it your name? (I assume you're using translate)

Don't bother.

**Pull request merged**
